# Changes here will be overwritten by Copier
_commit: 0.3.5
_src_path: gh:pdm-project/copier-pdm
author_email: pierre@marijon.fr
author_fullname: Pierre Marijon
author_username: natir
build_doc: false
copyright_date: '2022'
copyright_holder: Pierre Marijon
copyright_holder_email: pierre@marijon.fr
copyright_license: MIT
project_description: A python twitch chat bot for my twitch channel cam_doc
project_name: pycam_bot
python_package_distribution_name: pycam-bot
python_package_import_name: pycam_bot
python_package_requires_python: '>=3.7'
repository_name: pycam-bot
repository_namespace: natir
