name: Lints

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  Lints:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
          echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.set_variables.outputs.PIP_CACHE }}
            ${{ steps.set_variables.outputs.PDM_CACHE }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}

      - name: Check format
        run: pdm run black src --check
      - name: Check import order
        run: pdm run isort src --check
      - name: Check lint
        run: pdm run flake8
      - name: Check type
        run: pdm run mypy
